# Generated by Django 4.2.3 on 2023-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cake_text',
        ),
        migrations.AddField(
            model_name='order',
            name='cake_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Москва, метро Китай-Город', max_length=200, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(db_index=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(db_index=True, verbose_name='Время доставки'),
        ),
    ]
