# Generated by Django 4.2.3 on 2023-07-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_address',
            new_name='delivery_address',
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_name',
            field=models.CharField(default='Кастомный торт', max_length=30, verbose_name='Название торта'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='bakery.caketopping', verbose_name='Топпинг торта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bakery.user', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации заказа'),
        ),
    ]
