# Generated by Django 4.2.3 on 2023-07-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(blank=True, choices=[('1', 'Ежевика'), ('2', 'Малина'), ('3', 'Голубика'), ('4', 'Клубника')], max_length=30, null=True, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(blank=True, choices=[('1', 'Фисташки'), ('2', 'Безе'), ('3', 'Фундук'), ('4', 'Пекан'), ('5', 'Маршмеллоу'), ('6', 'Марципан')], max_length=30, null=True, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='shape',
            field=models.CharField(choices=[('1', 'Круг'), ('2', 'Квадрат'), ('3', 'Прямоугольник')], max_length=30, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(choices=[('1', 'Без'), ('2', 'Белый соус'), ('3', 'Карамельный'), ('4', 'Кленовый'), ('5', 'Черничный'), ('6', 'Молочный шоколад'), ('7', 'Клубничный')], max_length=30, verbose_name='Топпинг'),
        ),
    ]
