# Generated by Django 4.2.3 on 2023-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_rename_deliver_address_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.CharField(blank=True, max_length=50, verbose_name='Путь к изображению торта'),
        ),
    ]
