# Generated by Django 3.2.15 on 2023-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_alter_cake_berries_alter_cake_decor_alter_cake_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvetisementUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.CharField(max_length=20, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Рекламная ссылка',
                'verbose_name_plural': 'Рекламные ссылки',
            },
        ),
    ]
