# Generated by Django 3.2.15 on 2023-07-27 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_advetisementurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advetisementurl',
            name='link',
            field=models.CharField(max_length=20, verbose_name='Ссылка'),
        ),
        migrations.CreateModel(
            name='AdvetisementUrlCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_clicks', models.IntegerField(verbose_name='Количество')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='bakery.advetisementurl', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Количество просмотров',
                'verbose_name_plural': 'Количество просмотров',
            },
        ),
    ]
